name: Update Manifest on Develop Change

on:
  push:
    branches:
      - develop

jobs:
  detect-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Determine frontend image version
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-frontend/') }}
        id: frontend-version
        run: |
          CURRENT_VERSION=$(grep -oP 'codingalice/aws-wiki-front:\K[0-9]+\.[0-9]+' manifest/front/frontend.yaml)
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION=3.0
          fi
          NEW_VERSION=$(echo $CURRENT_VERSION + 1.0 | bc)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push Frontend Image
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-frontend/') }}
        run: |
          docker build -t codingalice/aws-wiki-front:${{ env.NEW_VERSION }} aws-wiki-frontend
          docker push codingalice/aws-wiki-front:${{ env.NEW_VERSION }}

      - name: Update frontend.yaml
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-frontend/') }}
        run: |
          sed -i 's|image: codingalice/aws-wiki-front:.*|image: codingalice/aws-wiki-front:${{ env.NEW_VERSION }}|' manifest/front/frontend.yaml

      - name: Determine backend image version
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-backend/') }}
        id: backend-version
        run: |
          CURRENT_VERSION=$(grep -oP 'codingalice/aws-wiki-back:\K[0-9]+\.[0-9]+' manifest/back/backend.yaml)
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION=2.0
          fi
          NEW_VERSION=$(echo $CURRENT_VERSION + 1.0 | bc)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build and Push Backend Image
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-backend/') }}
        run: |
          docker build -t codingalice/aws-wiki-back:${{ env.NEW_VERSION }} aws-wiki-backend
          docker push codingalice/aws-wiki-back:${{ env.NEW_VERSION }}

      - name: Update backend.yaml
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-backend/') }}
        run: |
          sed -i 's|image: codingalice/aws-wiki-back:.*|image: codingalice/aws-wiki-back:${{ env.NEW_VERSION }}|' manifest/back/backend.yaml

      - name: Commit and push changes
        if: |
          steps.changed-files.outputs.all_changed_files != '' &&
          (contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-frontend/') || 
           contains(steps.changed-files.outputs.all_changed_files, 'aws-wiki-backend/'))
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifest/front/frontend.yaml manifest/back/backend.yaml
          git commit -m "Update Docker images in manifest files"
          git push origin develop
